# Generated by Django 3.0.3 on 2020-02-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_searcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='search',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
